AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  DisplayCopNames: true
  DisplayStyleGuide: true

# Ensure debugger detection is enabled and treated seriously
Lint/Debugger:
  Enabled: true
  # severity error will cause rubocop --only to exit non-zero
  Severity: error

# keep other noisy style cops off or adjusted if you want
Layout/LineLength:
  Enabled: false
